export const FORMULARIO_OPERACION = 'FORMULARIO_OPERACION';
export const OBTENER_OPERACIONES = 'OBTENER_OPERACIONES';
export const AGREGAR_OPERACION = 'AGREGAR_OPERACION';
export const OPERACION_ACTUAL = 'OPERACION_ACTUAL';
export const ELIMINAR_OPERACION = 'ELIMINAR_OPERACION';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const ACTUALIZAR_OPERACION = 'ACTUALIZAR_OPERACION';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

